### ISSUE TITLE
Broken pulseaudio support on Telegram

### ISSUE THREAD

**Issue by nartes** [grishka/libtgvoip#42] opened 2018-03-29 04:04 UTC
https://github.com/telegramdesktop/tdesktop/issues/4219

**Comment by grishka** [comment] 2018-03-29 05:02
And so what? I couldn't ever reproduce anything like this...

**Comment by nartes** [comment] 2018-03-29 16:59
https://github.com/telegramdesktop/tdesktop/issues/4219#issuecomment-376997420

```plain
siarhei_hp% yaourt -Qi telegram-desktop
Name            : telegram-desktop
Version         : 1.2.14-2
Description     : Official Telegram Desktop client
Architecture    : x86_64
URL             : https://desktop.telegram.org/
Licenses        : GPL3
Groups          : None
Provides        : None
Depends On      : ffmpeg  hicolor-icon-theme  minizip  openal  qt5-base  qt5-imageformats  openssl
Optional Deps   : libnotify: desktop notifications [installed]
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 33.36 MiB
Packager        : Sven-Hendrik Haase <sh@lutzhaase.com>
Build Date      : Fri 23 Mar 2018 03:19:21 PM +03
Install Date    : Sat 24 Mar 2018 08:52:34 AM +03
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

siarhei_hp% yaourt -Si telegram-desktop
Repository      : community
Name            : telegram-desktop
Version         : 1.2.14-2
Description     : Official Telegram Desktop client
Architecture    : x86_64
URL             : https://desktop.telegram.org/
Licenses        : GPL3
Groups          : None
Provides        : None
Depends On      : ffmpeg  hicolor-icon-theme  minizip  openal  qt5-base  qt5-imageformats  openssl
Optional Deps   : libnotify: desktop notifications
Conflicts With  : None
Replaces        : None
Download Size   : 17.00 MiB
Installed Size  : 33.36 MiB
Packager        : Sven-Hendrik Haase <sh@lutzhaase.com>
Build Date      : Fri 23 Mar 2018 03:19:21 PM +03
Validated By    : MD5 Sum  SHA-256 Sum  Signature
```

I'm trying to write a simple unit test covering this issue. It's definitely within libtgvoip boundaries only.

**Comment by grishka** [comment] 2018-03-29 17:08
Well, I do acknowledge that this is my bug, but if only I had an idea where to start fixing it.

Which Linux distribution are you using? I've only ever tested on Ubuntu 12.04 on a VM and it certainly didn't crash like this.

**Comment by nartes** [comment] 2018-03-29 17:09
I've been experiencing this behaviour on Archlinux. It's been Xorg one time, and Wayland the other. Both times, the application either crashes or loads the PC. Pulseaudio is 11.1.

**Comment by nartes** [comment] 2018-03-31 08:49
Another stacktrace, seems like these are race conditions, that pulseaudio api warns about!
```plain
(gdb) where
#0  0x00007fbc5e62c860 in raise () at /usr/lib/libc.so.6
#1  0x00007fbc5e62dec9 in abort () at /usr/lib/libc.so.6
#2  0x00007fbc3658ef24 in pa_queue_pop () at /usr/lib/pulseaudio/libpulsecommon-11.1.so
#3  0x00007fbc3658d847 in  () at /usr/lib/pulseaudio/libpulsecommon-11.1.so
#4  0x00007fbc3658e7be in  () at /usr/lib/pulseaudio/libpulsecommon-11.1.so
#5  0x00007fbc367f204d in pa_mainloop_dispatch () at /usr/lib/libpulse.so.0
#6  0x00007fbc367f2280 in pa_mainloop_iterate () at /usr/lib/libpulse.so.0
#7  0x00007fbc367f2301 in pa_mainloop_run () at /usr/lib/libpulse.so.0
#8  0x00007fbc368006ae in  () at /usr/lib/libpulse.so.0
#9  0x00007fbc3659f81c in  () at /usr/lib/pulseaudio/libpulsecommon-11.1.so
#10 0x00007fbc5f2a008c in start_thread () at /usr/lib/libpthread.so.0
#11 0x00007fbc5e6ede7f in clone () at /usr/lib/libc.so.6
(gdb) info threads
  Id   Target Id         Frame 
  1    Thread 0x7fbc64e1bd00 (LWP 1867) "telegram-deskto" 0x00007fbc5e6e397b in poll () from /usr/lib/libc.so.6
  2    Thread 0x7fbc4ebe0700 (LWP 1870) "QXcbEventReader" 0x00007fbc5e6e397b in poll () from /usr/lib/libc.so.6
  3    Thread 0x7fbc450f7700 (LWP 1871) "dconf worker" 0x00007fbc5e6e397b in poll () from /usr/lib/libc.so.6
  4    Thread 0x7fbc448f6700 (LWP 1872) "gmain" 0x00007fbc5e6e397b in poll () from /usr/lib/libc.so.6
  5    Thread 0x7fbc3ffff700 (LWP 1873) "gdbus" 0x00007fbc5e6e397b in poll () from /usr/lib/libc.so.6
  6    Thread 0x7fbc37fff700 (LWP 1874) "QDBusConnection" 0x00007fbc5e6e397b in poll () from /usr/lib/libc.so.6
  7    Thread 0x7fbc3721e700 (LWP 1879) "QThread" 0x00007fbc5e6e397b in poll () from /usr/lib/libc.so.6
  8    Thread 0x7fbc35e53700 (LWP 1880) "QThread" 0x00007fbc5e6e397b in poll () from /usr/lib/libc.so.6
  9    Thread 0x7fbc35652700 (LWP 1881) "QThread" 0x00007fbc5e6e397b in poll () from /usr/lib/libc.so.6
  10   Thread 0x7fbc34e51700 (LWP 1883) "Qt bearer threa" 0x00007fbc5e6e397b in poll () from /usr/lib/libc.so.6
  11   Thread 0x7fbc1db21700 (LWP 1884) "MTP::internal::" 0x00007fbc5e6e397b in poll () from /usr/lib/libc.so.6
  121  Thread 0x7fbc07e25700 (LWP 3219) "MTP::internal::" 0x00007fbc5e6e397b in poll () from /usr/lib/libc.so.6
  124  Thread 0x7fbc1cefd700 (LWP 3222) "MTP::internal::" 0x00007fbc5e6e397b in poll () from /usr/lib/libc.so.6
  168  Thread 0x7fbc0be2d700 (LWP 3779) "QNetworkAccessM" 0x00007fbc5e6e397b in poll () from /usr/lib/libc.so.6
  514  Thread 0x7fbc05e21700 (LWP 9302) "QNetworkAccessM" 0x00007fbc5e6e397b in poll () from /usr/lib/libc.so.6
  660  Thread 0x7fbc07624700 (LWP 13162) "QNetworkAccessM" 0x00007fbc5e6e397b in poll () from /usr/lib/libc.so.6
  663  Thread 0x7fbc06622700 (LWP 13220) "voip-recv" 0x00007fbc5e6e57b3 in select () from /usr/lib/libc.so.6
  664  Thread 0x7fbc0a62a700 (LWP 13221) "voip-send" 0x00007fbc5f2a8cf6 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
  665  Thread 0x7fbc09e29700 (LWP 13222) "voip-tick" 0x00007fbc5e6bbb10 in nanosleep () from /usr/lib/libc.so.6
* 666  Thread 0x7fbc09628700 (LWP 13223) "threaded-ml" 0x00007fbc5e62c860 in raise () from /usr/lib/libc.so.6
  667  Thread 0x7fbc08626700 (LWP 13224) "threaded-ml" 0x00007fbc5e6e397b in poll () from /usr/lib/libc.so.6
  668  Thread 0x7fbc06e23700 (LWP 13225) "voip-recv" 0x00007fbc5f2a8cf6 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
  669  Thread 0x7fbc05620700 (LWP 13226) "opus_encoder" 0x00007fbc5f2a8cf6 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
  670  Thread 0x7fbc04e1f700 (LWP 13227) "opus_decoder" 0x00007fbc5f2a8cf6 in do_futex_
```

https://github.com/pulseaudio/pulseaudio/blob/master/src/pulse/thread-mainloop.h#L218

**Comment by nartes** [comment] 2018-03-31 08:50
```plain
(gdb) where
#0  0x00007fd369ddb860 in raise () at /usr/lib/libc.so.6
#1  0x00007fd369ddcec9 in abort () at /usr/lib/libc.so.6
#2  0x00007fd341d48f24 in pa_queue_pop () at /usr/lib/pulseaudio/libpulsecommon-11.1.so
#3  0x00007fd341d47847 in  () at /usr/lib/pulseaudio/libpulsecommon-11.1.so
#4  0x00007fd341d487be in  () at /usr/lib/pulseaudio/libpulsecommon-11.1.so
#5  0x00007fd341fac04d in pa_mainloop_dispatch () at /usr/lib/libpulse.so.0
#6  0x00007fd341fac280 in pa_mainloop_iterate () at /usr/lib/libpulse.so.0
#7  0x00007fd341fac301 in pa_mainloop_run () at /usr/lib/libpulse.so.0
#8  0x00007fd341fba6ae in  () at /usr/lib/libpulse.so.0
#9  0x00007fd341d5981c in  () at /usr/lib/pulseaudio/libpulsecommon-11.1.so
#10 0x00007fd36aa4f08c in start_thread () at /usr/lib/libpthread.so.0
#11 0x00007fd369e9ce7f in clone () at /usr/lib/libc.so.6
(gdb) info threads
  Id   Target Id         Frame 
  1    Thread 0x7fd3705cad00 (LWP 13282) "telegram-deskto" 0x00007fd36aa5045d in pthread_join () from /usr/lib/libpthread.so.0
  2    Thread 0x7fd35a38f700 (LWP 13284) "QXcbEventReader" 0x00007fd369e9297b in poll () from /usr/lib/libc.so.6
  3    Thread 0x7fd3509bf700 (LWP 13285) "dconf worker" 0x00007fd369e9297b in poll () from /usr/lib/libc.so.6
  4    Thread 0x7fd34bfff700 (LWP 13286) "gmain" 0x00007fd369e9297b in poll () from /usr/lib/libc.so.6
  5    Thread 0x7fd34b7fe700 (LWP 13287) "gdbus" 0x00007fd369e9297b in poll () from /usr/lib/libc.so.6
  6    Thread 0x7fd3437b9700 (LWP 13290) "QDBusConnection" 0x00007fd369e9297b in poll () from /usr/lib/libc.so.6
  7    Thread 0x7fd3429d8700 (LWP 13295) "QThread" 0x00007fd369e9297b in poll () from /usr/lib/libc.so.6
  8    Thread 0x7fd34160d700 (LWP 13296) "QThread" 0x00007fd369e9297b in poll () from /usr/lib/libc.so.6
  9    Thread 0x7fd340e0c700 (LWP 13297) "QThread" 0x00007fd369e9297b in poll () from /usr/lib/libc.so.6
  10   Thread 0x7fd337fff700 (LWP 13301) "Qt bearer threa" 0x00007fd369e9297b in poll () from /usr/lib/libc.so.6
  11   Thread 0x7fd335320700 (LWP 13305) "MTP::internal::" 0x00007fd369e9297b in poll () from /usr/lib/libc.so.6
  12   Thread 0x7fd334b1f700 (LWP 13309) "QNetworkAccessM" 0x00007fd369e9297b in poll () from /usr/lib/libc.so.6
  15   Thread 0x7fd3314df700 (LWP 13315) "voip-tick" 0x00007fd369e6ab10 in nanosleep () from /usr/lib/libc.so.6
* 16   Thread 0x7fd330cde700 (LWP 13316) "threaded-ml" 0x00007fd369ddb860 in raise () from /usr/lib/libc.so.6
  17   Thread 0x7fd2e3fff700 (LWP 13317) "threaded-ml" 0x00007fd369e9297b in poll () from /usr/lib/libc.so.6
  18   Thread 0x7fd2d77fe700 (LWP 13318) "voip-recv" 0x00007fd36aa57cf6 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
  19   Thread 0x7fd2d6ffd700 (LWP 13319) "opus_encoder" 0x00007fd36aa57cf6 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
  20   Thread 0x7fd2d67fc700 (LWP 13320) "opus_decoder" 0x00007fd36aa57cf6 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
```

**Comment by nartes** [comment] 2018-03-31 09:14
One more
```plain
(gdb) where
#0  0x00007ffff17ab860 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff17acec9 in abort () at /usr/lib/libc.so.6
#2  0x00007fffc53d4f24 in pa_queue_pop () at /usr/lib/pulseaudio/libpulsecommon-11.1.so
#3  0x00007fffc53d3847 in  () at /usr/lib/pulseaudio/libpulsecommon-11.1.so
#4  0x00007fffc53d47be in  () at /usr/lib/pulseaudio/libpulsecommon-11.1.so
#5  0x00007fffc563804d in pa_mainloop_dispatch () at /usr/lib/libpulse.so.0
#6  0x00007fffc5638280 in pa_mainloop_iterate () at /usr/lib/libpulse.so.0
#7  0x00007fffc5638301 in pa_mainloop_run () at /usr/lib/libpulse.so.0
#8  0x00007fffc56466ae in  () at /usr/lib/libpulse.so.0
#9  0x00007fffc53e581c in  () at /usr/lib/pulseaudio/libpulsecommon-11.1.so
#10 0x00007ffff241f08c in start_thread () at /usr/lib/libpthread.so.0
#11 0x00007ffff186ce7f in clone () at /usr/lib/libc.so.6
(gdb) info threads
  Id   Target Id         Frame 
  1    Thread 0x7ffff7f98100 (LWP 1112) "telegram-deskto" 0x00007ffff35dafaf in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
  2    Thread 0x7fffe1d5b700 (LWP 1120) "QXcbEventReader" 0x00007ffff186297b in poll () from /usr/lib/libc.so.6
  3    Thread 0x7fffd7ee9700 (LWP 1121) "dconf worker" 0x00007ffff186297b in poll () from /usr/lib/libc.so.6
  4    Thread 0x7fffd76e8700 (LWP 1122) "gmain" 0x00007ffff186297b in poll () from /usr/lib/libc.so.6
  5    Thread 0x7fffd6ee7700 (LWP 1123) "gdbus" 0x00007ffff186297b in poll () from /usr/lib/libc.so.6
  6    Thread 0x7fffd64ca700 (LWP 1124) "QDBusConnection" 0x00007ffff186297b in poll () from /usr/lib/libc.so.6
  10   Thread 0x7fffc6064700 (LWP 1130) "QThread" 0x00007ffff186297b in poll () from /usr/lib/libc.so.6
  11   Thread 0x7fffc4c99700 (LWP 1131) "QThread" 0x00007ffff186297b in poll () from /usr/lib/libc.so.6
  12   Thread 0x7fffbffff700 (LWP 1132) "QThread" 0x00007ffff186297b in poll () from /usr/lib/libc.so.6
  14   Thread 0x7fffbf7fe700 (LWP 1134) "Qt bearer threa" 0x00007ffff186297b in poll () from /usr/lib/libc.so.6
  15   Thread 0x7fffbc91b700 (LWP 1135) "MTP::internal::" 0x00007ffff186297b in poll () from /usr/lib/libc.so.6
  17   Thread 0x7fffaf7fe700 (LWP 1137) "QNetworkAccessM" 0x00007ffff186297b in poll () from /usr/lib/libc.so.6
  36   Thread 0x7fff5f7fe700 (LWP 1163) "voip-recv" 0x00007ffff18647b3 in select () from /usr/lib/libc.so.6
  37   Thread 0x7fffad215700 (LWP 1164) "voip-send" 0x00007ffff2427cf6 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
  38   Thread 0x7fffaffff700 (LWP 1165) "voip-tick" 0x00007ffff183ab10 in nanosleep () from /usr/lib/libc.so.6
* 39   Thread 0x7fffaec19700 (LWP 1166) "threaded-ml" 0x00007ffff17ab860 in raise () from /usr/lib/libc.so.6
  40   Thread 0x7fffae418700 (LWP 1167) "threaded-ml" 0x00007ffff186297b in poll () from /usr/lib/libc.so.6
  41   Thread 0x7fffadc17700 (LWP 1168) "voip-recv" 0x00007ffff2427cf6 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
  42   Thread 0x7fff5effd700 (LWP 1169) "opus_encoder" 0x00007ffff2427cf6 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
  43   Thread 0x7fff5e7fc700 (LWP 1170) "opus_decoder" 0x00007ffff2427cf6 in do_futex_wait.constprop () from /usr/lib/libpthread.so.0
(gdb) 
```

**Comment by nartes** [comment] 2018-03-31 09:15
I've just called a person and been constantly toggling the mute button!
At some point one of the clients crashes!
It's either sensitivity to the non-uniform audio packets timing, or
a bad handling of muting.

**Comment by nartes** [comment] 2018-03-31 09:17
```plain
siarhei_hp% yaourt -Qi telegram-desktop
Name            : telegram-desktop
Version         : 1.2.15-1
Description     : Official Telegram Desktop client
Architecture    : x86_64
URL             : https://desktop.telegram.org/
Licenses        : GPL3
Groups          : None
Provides        : None
Depends On      : ffmpeg  hicolor-icon-theme  minizip  openal  qt5-base  qt5-imageformats  openssl
Optional Deps   : libnotify: desktop notifications [installed]
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 33.36 MiB
Packager        : Sven-Hendrik Haase <sh@lutzhaase.com>
Build Date      : Mon 26 Mar 2018 12:39:20 PM +03
Install Date    : Sat 31 Mar 2018 12:00:18 PM +03
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Comment by danog** [comment] 2018-03-31 09:18
@grishka if you need help reproducing I suggest you call https://t.me/magnaluna: probably because of the high bitrates, calling her triggers a pulseaudio error in one call out of ten.
Rapidly making and closing calls also helps apparently.

**Comment by llybin** [comment] 2018-05-16 12:53
I have same a problem for a long time.

**Comment by cknost** [comment] 2018-05-17 16:07
Same Problem.

**Comment by backtozero** [comment] 2018-06-18 07:05
+1 Ubuntu 16.04

**Comment by grishka** [comment] 2018-07-01 21:02
I've finally managed to reproduce this (on a fresh install of Kubuntu 18.04 if that matters), I'll push a fix shortly.

I wasn't using the threaded main loop thing correctly.

**Closed as completed** 2018-07-01 21:42 UTC

**Comment by grishka** [comment] 2018-07-14 02:04
TDesktop 1.3.10 is out. Please update and check if this issue is actually fixed.

**Comment by backtozero** [comment] 2018-07-14 02:51
Is there any echo-service in telegram to make test calls?

**Comment by grishka** [comment] 2018-07-14 02:56
There's no Skype's "echo123", but there's https://t.me/magnaluna radio thing I personally use for testing.

**Comment by backtozero** [comment] 2018-07-14 10:44
Yeah looks good now. No crash anymore.  Thank you.

**Comment by llybin** [comment] 2018-07-17 18:19
Crashes is solved, but calls still doen't works, open new issue?

```
D/tgvoip: === Updating voip config ===
V/tgvoip: audio_bitrate_step_decr -> 1000.000000
V/tgvoip: audio_bitrate_step_incr -> 1000.000000
V/tgvoip: audio_congestion_window -> 1024.000000
V/tgvoip: audio_frame_size -> 60.000000
V/tgvoip: audio_init_bitrate -> 16000.000000
V/tgvoip: audio_init_bitrate_edge -> 8000.000000
V/tgvoip: audio_init_bitrate_gprs -> 8000.000000
V/tgvoip: audio_init_bitrate_saving -> 8000.000000
V/tgvoip: audio_max_bitrate -> 20000.000000
V/tgvoip: audio_max_bitrate_edge -> 16000.000000
V/tgvoip: audio_max_bitrate_gprs -> 8000.000000
V/tgvoip: audio_max_bitrate_saving -> 8000.000000
V/tgvoip: force_tcp -> false
V/tgvoip: jitter_losses_to_reset -> 20.000000
V/tgvoip: jitter_max_delay_20 -> 25.000000
V/tgvoip: jitter_max_delay_40 -> 15.000000
V/tgvoip: jitter_max_delay_60 -> 10.000000
V/tgvoip: jitter_max_slots_20 -> 50.000000
V/tgvoip: jitter_max_slots_40 -> 30.000000
V/tgvoip: jitter_max_slots_60 -> 20.000000
V/tgvoip: jitter_min_delay_20 -> 6.000000
V/tgvoip: jitter_min_delay_40 -> 4.000000
V/tgvoip: jitter_min_delay_60 -> 2.000000
V/tgvoip: jitter_resync_threshold -> 0.500000
V/tgvoip: use_system_aec -> true
V/tgvoip: use_system_ns -> true
W/tgvoip: Set remote endpoints, allowP2P=1, connectionMaxLayer=65
V/tgvoip: Adding endpoint: 91.108.16.4:522, UDP
V/tgvoip: Adding endpoint: 91.108.16.3:534, UDP
V/tgvoip: Adding endpoint: 91.108.12.2:535, UDP
V/tgvoip: Adding endpoint: 91.108.12.5:539, UDP
V/tgvoip: Adding endpoint: 91.108.8.2:540, UDP
V/tgvoip: Adding endpoint: 91.108.8.3:526, UDP
I/tgvoip: update data saving mode, config 0, enabled 0, reqd by peer 0
W/tgvoip: Starting voip controller
E/tgvoip: error creating socket: 97 / Address family not supported by protocol
V/tgvoip: Call state changed to 4
V/tgvoip: Call state changed to 2
D/tgvoip: Entered VoIPController::Stop
D/tgvoip: before shutdown socket
D/tgvoip: before join sendThread
D/tgvoip: before join recvThread
D/tgvoip: before join tickThread
D/tgvoip: Before stop audio I/O
D/tgvoip: Left VoIPController::Stop
D/tgvoip: Entered VoIPController::~VoIPController
D/tgvoip: before close socket
D/tgvoip: before delete audio input
D/tgvoip: before delete encoder
D/tgvoip: before delete echo canceller
D/tgvoip: Left VoIPController::~VoIPController
```

**Comment by grishka** [comment] 2018-07-17 18:21
You've disabled the IPv6 stack in your kernel, didn't you?

**Comment by llybin** [comment] 2018-07-17 19:06
I enabled IPv6, calls started to work, thank you!
